language: d

d:
  - dmd
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.2
  - ldc
  - ldc-1.0.0
  - ldc-0.17.3
  - gdc

sudo: false

script:
  - dub build --build=release --config=library
  - dub test --build=unittest --config=unittest
  - dub run --build=release --config=quickstartExample
  - dub run --build=release --config=qualifiersExample
  - dub run --build=release --config=arrayCompletionExample
  - dub run --build=release --config=annotationsExample
  - dub run --build=release --config=applicationContextExample
  - dub run --build=release --config=registerOnResolveExample
  - dub run --build=release --config=constructorInjectionExample
  - dub run --build=release --config=valueInjectionExample
  - dub run --build=release --config=postConstructorPreDestructorExample
